# Generated by Django 3.2.10 on 2023-02-10 20:29

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название книги')),
                ('book', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_published', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CategoryBooks',
            fields=[
                ('book_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=225, unique=True, verbose_name='Название Категория')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Категория для книг',
                'verbose_name_plural': 'Категории для книг',
                'ordering': ['-is_published'],
            },
        ),
        migrations.CreateModel(
            name='CategoryPost',
            fields=[
                ('post_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=225, unique=True, verbose_name='Название Категория')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Категория для поста',
                'verbose_name_plural': 'Категории для постов',
                'ordering': ['-is_published'],
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Категория события')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Категоря памятной даты',
                'verbose_name_plural': 'Категории памятных дат',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, verbose_name='Название')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='media/pic/%Y/%m/%d/', verbose_name='Картинка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Quotas',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='ФИО Деятеля')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Цитата')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Цитата',
                'verbose_name_plural': 'Цитаты',
                'ordering': ['-is_published'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='Заголовок новости')),
                ('url', models.SlugField(max_length=255, unique=True)),
                ('text', ckeditor.fields.RichTextField()),
                ('views', models.PositiveIntegerField(blank=True, default=0)),
                ('pict', models.ImageField(blank=True, null=True, upload_to='media/pic/%Y/%m/%d/', verbose_name='Картинка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='psywings.categorypost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-is_published'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('message', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, verbose_name='Название сайта')),
                ('url', models.URLField(verbose_name='URL Сайта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание сайта')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сайт - URL',
                'verbose_name_plural': 'Сайты - URLs',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='FriendLinks',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, verbose_name='Название сайта')),
                ('url', models.URLField(verbose_name='URL Сайта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание сайта')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'URL сайта друзей',
                'verbose_name_plural': 'URL сайтов друзей',
                'ordering': ['-is_published'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок события')),
                ('url', models.SlugField(max_length=255, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='media/eventpic/%Y/%m/%d/', verbose_name='Картинка')),
                ('text', ckeditor.fields.RichTextField()),
                ('event_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата события')),
                ('manager', models.CharField(blank=True, max_length=60)),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('event_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='psywings.eventcategory')),
            ],
            options={
                'verbose_name': 'Памятная дата',
                'verbose_name_plural': 'Памятные даты',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The Term being described', max_length=128, verbose_name='The Term')),
                ('text', models.TextField(help_text='The description of the term being explained', verbose_name='The Explanation')),
                ('alpha_position', models.CharField(choices=[('а', 'а'), ('б', 'б'), ('в', 'в'), ('г', 'г'), ('д', 'д'), ('е', 'е'), ('ж', 'ж'), ('з', 'з'), ('и', 'и'), ('й', 'й'), ('к', 'к'), ('л', 'л'), ('м', 'м'), ('н', 'н'), ('о', 'о'), ('п', 'п'), ('р', 'р'), ('с', 'с'), ('т', 'т'), ('у', 'у'), ('ф', 'ф'), ('х', 'х'), ('ц', 'ц'), ('ч', 'ч'), ('ш', 'ш'), ('щ', 'щ'), ('ъ', 'ъ'), ('ы', 'ы'), ('ь', 'ь'), ('э', 'э'), ('ю', 'ю'), ('я', 'я')], db_index=True, help_text='Show this entry under which Alphabet position', max_length=2, verbose_name='Alphabet Position')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись в словаре',
                'verbose_name_plural': 'Все записи в словаре',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psywings.question')),
            ],
        ),
    ]
