# Generated by Django 3.2.10 on 2023-02-12 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psywings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, verbose_name='Название категории')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='gallery',
            name='image_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='psywings.categorygallery'),
        ),
    ]
