# Generated by Django 3.2.10 on 2023-02-12 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageinfo',
            options={'ordering': ['created_at'], 'verbose_name': 'Landing Page', 'verbose_name_plural': 'Landing Page'},
        ),
    ]
