# Generated by Django 4.1.7 on 2023-03-05 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_suvorov'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorybooks',
            options={'ordering': ['created_at'], 'verbose_name': 'Категория для книг', 'verbose_name_plural': 'Категории для книг'},
        ),
        migrations.AlterModelOptions(
            name='suvorov',
            options={'ordering': ['title'], 'verbose_name': 'Об авторе', 'verbose_name_plural': 'Об авторе'},
        ),
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.categorybooks'),
        ),
    ]
